### ISSUE TITLE
Cannot contribute

### ISSUE THREAD

**Issue by traubisoda** [spatie/laravel-server-side-rendering#10]
Hi!

First, thanks for this awesome package! :)

I'd like to suggest a few little changes to the readme that would make it easier for newcomers to set the package up, but I can't push to the repo, so I couldn't make a PR.

This is the error I got: 
remote: Permission to spatie/laravel-server-side-rendering.git denied to traubisoda.
fatal: unable to access 'https://github.com/spatie/laravel-server-side-rendering.git/': The requested URL returned error: 403

In case this repo is not open to pull requests, the changes I'd suggest to the readme:
The link to the examples is broken.
For me, it was not clear, that the NODE_ENV env variable is to be set in the .env file or in the OS.

**Comment by sebastiandedeyne** [comment]
Hi @traubisoda,

Thanks for wanting to contribute!

There's nothing special with this repository, we definitely accept pull requests! Not sure what's going on... Are you sure your SSH key is set up correctly and all?

**Comment by traubisoda** [comment]
I figured it out, my bad :)
