### ISSUE TITLE
How can I solve this?

### ISSUE THREAD

**Issue by fmcdigital** [spatie/laravel-server-side-rendering#13]
```
ErrorException (E_ERROR)
The command "/usr/local/bin/node /Users/lucassimines/Laravel/Dashboard New/storage/app/ssr/f2d73b9786b42d203679a6a382d15b85.js" failed. Exit Code: 1(General error) Working directory: /Users/lucassimines/Laravel/Dashboard New/public Output: ================ Error Output: ================ module.js:538 throw err; ^ Error: Cannot find module '/Users/lucassimines/Laravel/Dashboard' at Function.Module._resolveFilename (module.js:536:15) at Function.Module._load (module.js:466:25) at Function.Module.runMain (module.js:676:10) at startup (bootstrap_node.js:187:16) at bootstrap_node.js:608:3 (View: /Users/lucassimines/Laravel/Dashboard New/resources/views/frontend/index.blade.php)
```

**Comment by sebastiandedeyne** [comment]
Could you share more info on the issue so I can search for the cause? Please share as much info from the following:

- `package.json`
- Webpack/Mix/... configuration
- Blade view where `ssr` is called
- `ssr.php` config file
- Your JavaScript files

**Comment by sebastiandedeyne** [comment]
Gonna close this due to inactivity, feel free to reopen if you're still experiencing issues.

**Comment by SeanConnell93** [comment]
The command "/c/Program Files/nodejs/node C:\xampp\htdocs\Agrirecruit_Laravel\storage\app/ssr\c244232e15965255150ad76e7d13d123.js" failed. Exit Code: 1(General error) Working directory: C:\xampp\htdocs\Agrirecruit_Laravel\public Output

I've been stuck on the same error for the past few days and can't figure it out. 
Note: I'm using windows 10

I ran `which node` to get node path
I've set the `NODE_PATH="/c/Program Files/nodejs/node"`

`APP_ENV=production`

Here's my files.

**package.json** 

`"dependencies": {
        "vee-validate": "^2.0.9",
        "vue": "^2.5.7",
        "vue-head": "^2.0.12",
        "vue-router": "^3.0.1",
        "vue-server-renderer": "^2.5.16",
        "vue-the-mask": "^0.11.1",
        "vue-wysiwyg": "^1.7.2",
        "vue2-editor": "^2.5.0",
        "vuex": "^3.0.1"
    }`

**mix**

`mix.js('resources/assets/js/app-client.js', 'public/js')
    .js('resources/assets/js/app-server.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sourceMaps().version();`

**Blade**

`<script type="text/javascript" defer src="{{ mix('js/app-client.js') }}"></script>`

`<main class="container-fuild" id="app">
            {!! ssr("js/app-server.js")->render() !!}
        </main>`

The I didn't change anything in the ssr.php 

`return [

    'enabled' => env('APP_ENV') === 'production',

    'debug' => env('APP_DEBUG', false),

    'mix' => true,

    'engine' => \Spatie\Ssr\Engines\Node::class,

    'node' => [
        'node_path' => env('NODE_PATH', '/usr/local/bin/node'),
        'temp_path' => storage_path('app/ssr'),
    ],

    'context' => [],

    'env' => [
        'NODE_ENV' => 'production',
        'VUE_ENV' => 'server',
    ],
];`

**Client.js** 

`import app from './app'; app.$mount('#app');`

**Server.js**

`import app from './app';
import renderVueComponentToString from 'vue-server-renderer/basic';
renderVueComponentToString(app, (err, res) => {
    if (err) {
        throw new Error(err);
    }
    dispatch(res);
});`
