### ISSUE TITLE
Object of class Spatie\Ssr\Renderer could not be converted to string

### ISSUE THREAD

**Issue by luhegi** [spatie/laravel-server-side-rendering#14]
@sebastiandedeyne did i miss something?
Object of class Spatie\Ssr\Renderer could not be converted to string

here the error line
```
<?php echo Ssr::entry('js/app-server.js'); ?>
```

**Comment by luhegi** [comment]
sorry my bad.
looks like i haven't run 'npm run dev'

**Comment by luhegi** [comment]
i still have same issue after i run npm run dev, i checked app-server.js is in "public/js/app-server.js" now
Do you have any where i could go wrong? @sebastiandedeyne

**Comment by sebastiandedeyne** [comment]
Hi @luhegi,

Apparently the readme wasn't updated with the latest API changes. I fixed that. You need to explicitly call `render`.

<?php echo Ssr::entry('js/app-server.js')->render(); ?>
