### ISSUE TITLE
dispatch() function in entry-server.js

### ISSUE THREAD

**Issue by eleibu** [spatie/laravel-server-side-rendering#17]
Thanks very much for the code.

I'm trying to use it to implement SSR with React. I'm struggling with the `dispatch()` function in entry-server.js. Where does this function come from? It isn't native JS and doesn't seem to come from App, React or ReactDOMServer.

Any help would be much appreciated.

**Comment by sebastiandedeyne** [comment]
The `dispatch` implementation depends on the engine. It's a way to share output between JS and PHP.

There's a `getDispatchHandler` method on the `Engine` interface

https://github.com/spatie/server-side-rendering/blob/0df569c9d559689a257d714fb79b2286b8d0b599/src/Engine.php#L9

With Node, `dispatch` uses `console.log`

https://github.com/spatie/server-side-rendering/blob/0df569c9d559689a257d714fb79b2286b8d0b599/src/Engines/Node.php#L41-L44

With V8, `dispatch` uses `print`

https://github.com/spatie/server-side-rendering/blob/0df569c9d559689a257d714fb79b2286b8d0b599/src/Engines/V8.php#L35-L38
