### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mfissehaye** [spatie/laravel-server-side-rendering#19]
`ReferenceError: window is not defined`
I am getting this error when I run it on a digitalocean server. And there are several references to window on the built code for entry-server.js. I am following the example related to this repo.

**Comment by sebastiandedeyne** [comment]
We're not injecting anything with `window`. Does your code reference `window` anywhere?

Is the error on the server or in the client?

Also, please share as much code as possible.

**Comment by sebastiandedeyne** [comment]
Closing this for now, feel free to reopen with more details if you're still experiencing issues.

**Comment by Mixpeal** [comment]
@sebastiandedeyne , i have a code that is referencing both document and windows, is there any tweak for that?
