### ISSUE TITLE
Patch / Polyfill for DOM globals like document / window

### ISSUE THREAD

**Issue by youanden** [spatie/laravel-server-side-rendering#20]
Has anyone resolved issues relating to third party modules using these globals?

I know that I can refactor out the includes for these third party dependencies with a 
```if(typeof window !== 'undefined') { }```

condition but am wondering if there is a more automatic solution.

Thanks!

**Comment by sebastiandedeyne** [comment]
Assuming you're using something like React or Vue, the correct solution to this is only using `window` in lifecycle hooks that never are run on the server.

With React, that'd be the `componentDidMount` hook, with Vue, `mounted`. 

Part of Vue's SSR guide:

> Since there are no dynamic updates, of all the lifecycle hooks, only beforeCreate and created will be called during SSR. This means any code inside other lifecycle hooks such as beforeMount or mounted will only be executed on the client.

> Another thing to note is that you should avoid code that produces global side effects in beforeCreate and created, for example setting up timers with setInterval. In client-side only code we may setup a timer and then tear it down in beforeDestroy or destroyed. However, because the destroy hooks will not be called during SSR, the timers will stay around forever. To avoid this, move your side-effect code into beforeMount or mounted instead.

https://ssr.vuejs.org/en/universal.html

Hope this helps!
