### ISSUE TITLE
This package has some problems when the project is deployed trough Envoyer

### ISSUE THREAD

**Issue by dyegonery** [spatie/laravel-server-side-rendering#24]
Hey.

I'm using this package in one of my projects. It worked perfectly, with one caveat. My project is deployed with Envoyer. i'm using this webpack config:

```
const { mix } = require('laravel-mix');
var nodeExternals = require('webpack-node-externals');

mix.setPublicPath('public/js/ssr')
    .js('resources/assets/js/search-app.js', 'public/js/ssr/')
    .js('resources/assets/js/entry-server.js', 'public/js/ssr/');

mix.webpackConfig(
    {
        resolve: {
            alias: {
                vue$: 'vue/dist/vue.runtime.common.js',
            },
        },
        name: "server",
        externals: [nodeExternals()],
        target: "node"
    }
);

if (!mix.inProduction) {
    mix.webpackConfig.devtool = 'source-map';
    mix.sourceMaps();
}
```

The server script isn't executed on the server, because it is placed on storage/app/ssr. Since the storage folder is symlinked on Envoyer, I see a lot of "Cannot find module XXXX" with the require() on the bundle when the server script is executed.

What I did to solve this what changing the node `temp_path` to something inside the public folder on the current release. 

Just thought it can be useful to make this thread in case anyone has the same issue, or if there's any other "cleaner" fix for this.

**Comment by sebastiandedeyne** [comment]
Not fully following the issue, doesn't webpack bundle the modules in the build? How does the file location change this?

**Comment by dyegonery** [comment]
@sebastiandedeyne Not when you're using something like https://github.com/liady/webpack-node-externals
