### ISSUE TITLE
Node path on windows

### ISSUE THREAD

**Issue by Sjoerrdd** [spatie/laravel-server-side-rendering#25]
Hello,

I have followed all the steps in the documentation, but are still returning to the fallback.

My .env: `NODE_PATH="C:\Program Files\nodejs"`

Blade:

```
<!doctype html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel</title>
    <link rel="stylesheet" href="{{ mix('css/app.css') }}">
    <script defer src="{{ mix('js/app-client.js') }}"></script>
  </head>
  <body>
    {!! ssr('js/app-server.js')->fallback('<div id="app"></div>')->render() !!}
  </body>
</html>
```

**Comment by Sjoerrdd** [comment]
Error: 

```
The command "node C:\Users\Sjoerd\Documents\GitHub\Poll\storage\app/ssr\4f7672d21af17a02b5dcaac514524d6f.js" failed. Exit Code: 1(General error) Working directory: C:\Users\Sjoerd\Documents\GitHub\Poll\public Output: ================ Error Output: ================ 'node' is not recognized as an internal or external command, operable program or batch file. (View: C:\Users\Sjoerd\Documents\GitHub\Poll\resources\views\home.blade.php)
```

When I run node in the command prompt, I get the Node CLI.

**Comment by MicroDreamIT** [comment]
I am having same problem

**Comment by G-Bruin** [comment]
me too, how to fix it

**Comment by G-Bruin** [comment]
> me too
if you use windows, ```NODE_PATH=node```

**Comment by G-Bruin** [comment]
> me too

if you use windwos, ```NODE_PATH=node```

**Comment by Sjoerrdd** [comment]
Thanks @G-Bruin! :)

**Comment by MicroDreamIT** [comment]
I have used NODE_PATH=node but did not work

**Comment by martinwang2002** [comment]
For `NODE_PATH=node` on windows 10
Using command `php aritsan serve` throws `'node' is not recognized as an internal or external command, operable program or batch file.`
While using Xampp (typically apache, other servers not tested), SSR is working.

**Comment by hadishahpuri** [comment]
I'm using wamp in windows and still the same error: 'node' is not recognized as an internal or external command, operable program or batch file' while typing node in shell works
