### ISSUE TITLE
Support mix.extract() ?

### ISSUE THREAD

**Issue by PotsonHumer** [spatie/laravel-server-side-rendering#26]
Thank you make this awesome package !

One question; is this package support mix.extract?
how can I make manifest.js & vendor.js work in SSR?

Please help ! thanks~

**Comment by ievgenklymenko** [comment]
Correct me if I'm wrong, but logically, extracting only makes sense for client-side. I was about to do extract on server-side myself then I realized it just won't have any impact. Your server isn't re-downloading extra things anyway. In production, you don't recompile that often. In development, if you are using npm --watch script, compilation time saved will be miserable. Or am I missing something?

**Comment by khejit** [comment]
I think that you have to run two processes, with different mix() usage. For example:
`"build": "npm run buildServerPart && npm run buildClientPart",
"buildServerPart": "node node_modules/cross-env/dist/bin/cross-env.js process.env.ssrLayer=server NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
"buildClientPart": "node node_modules/cross-env/dist/bin/cross-env.js process.env.ssrLayer=client NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",`
Then in webpack.mix.js you can check for the variable ssrLayer which is different in each process:
`if (process.env.ssrLayer === 'server') {
    require(`${__dirname}/webpack.mix.server.js`);
} else {
    require(`${__dirname}/webpack.mix.client.js`);
}`
In webpack.mix.server.js you can use mix() with no .extract(), and in webpack.mix.client.js you can chain .extract().
But there has to be a better way.

**Comment by mpatzner** [comment]
Here's a more detailed explanation of this concept: http://www.compulsivecoders.com/tech/how-to-build-multiple-vendors-using-laravel-mix/
