### ISSUE TITLE
Node+React How To Catch Tree Errors?

### ISSUE THREAD

**Issue by ievgenklymenko** [spatie/laravel-server-side-rendering#31]
Hi, nice package but I'm struggling with debugging;

React componentDidCatch doesn't fire on server, so some workaround is necessary for ssr; how can we catch tree render errors using this library and node?
People recommend wrapping renderToString in try-catch, but it doesn't catch all errors and renderToString just returns empty string if something failed, most of the times

What is possible to do?

**Comment by sebastiandedeyne** [comment]
I'm afraid I don't have enough experience with React SSR to help here. I recommend you skim some React forums to see how people deal with SSR failures, since this isn't something that we can do much about in the package.
