### ISSUE TITLE
how to use axios in ssr

### ISSUE THREAD

**Issue by G-Bruin** [spatie/laravel-server-side-rendering#32]
```
export default {
    data () {
        return {
            items: []
        }
    },
    created () {
        this.login()
    },
    methods: {
        login () {
            let self = this
            this.http.get('test')
            .then(function (response) {
                self.items = response.data
            })
            .catch(function (error) {
                console.log(error);
            });

        }
    }
};
```
![image](https://user-images.githubusercontent.com/20853074/50952803-818f4b80-14ec-11e9-85a9-1c5ba0c5dc3b.png)

**Comment by andrey-v** [comment]
XMLHttpRequest is defined on the client only. I solved the problem by setting target='node' in the webpack config.
```
    mix
        .js('./resources/js/entry-server.js', 'public/js')
        .webpackConfig(() => ({
            target: 'node', // By default target = web
            resolve: {
                extensions: ['.js', '.vue', '.json'],
                alias: {
                    '@': __dirname + '/resources/js'
                },
            },
        }));
```

**Comment by G-Bruin** [comment]
thx, i try it later

**Comment by vintprox** [comment]
@andrey-v What's about client then? I wonder if I can split webpack configurations in mix one?

**Comment by andrey-v** [comment]
@vintprox Yes, you can. For example, I changed the package.json file by adding the SSR variable
```
{
    "private": true,
    "scripts": {
        "dev": "SSR=1 npm run development && npm run development",
...
```


and split mix file:
```
let mix = require('laravel-mix');

if (process.env.SSR === '1') {
    // Server part
    mix
        .js('./resources/js/entry-server.js', 'public/js')
        .webpackConfig(() => ({
            target: 'node',
            resolve: {
                extensions: ['.js', '.vue', '.json'],
                alias: {
                    '@': __dirname + '/resources/js',
                },
            },
        }));

// other code

    return;
}

// Client part
mix
    .js('./resources/js/entry-client.js', 'public/js');

```

**Comment by andrey-v** [comment]
@vintprox Yes, you can. For example, I changed the package.json file by adding the SSR variable
```
{
    "private": true,
    "scripts": {
        "dev": "SSR=1 npm run development && npm run development",
...
```


and split mix file:
```
let mix = require('laravel-mix');

if (process.env.SSR === '1') {
    // Server part
    mix
        .js('./resources/js/entry-server.js', 'public/js')
        .webpackConfig(() => ({
            target: 'node',
            resolve: {
                extensions: ['.js', '.vue', '.json'],
                alias: {
                    '@': __dirname + '/resources/js',
                },
            },
        }));

// other code

    return;
}

// Client part
mix
    .js('./resources/js/entry-client.js', 'public/js');

```

**Comment by vintprox** [comment]
> @vintprox Yes, you can. For example, I changed the package.json file by adding the SSR variable
> 
> ```
> {
>     "private": true,
>     "scripts": {
>         "dev": "SSR=1 npm run development && npm run development",
> ...
> ```
> and split mix file code:
> 
> ```
> let mix = require('laravel-mix');
> 
> if (process.env.SSR === '1') {
>     // Server part
>     mix
>         .js('./resources/js/entry-server.js', 'public/js')
>         .webpackConfig(() => ({
>             target: 'node',
>             resolve: {
>                 extensions: ['.js', '.vue', '.json'],
>                 alias: {
>                     '@': __dirname + '/resources/js',
>                 },
>             },
>         }));
> 
> // other code
> 
>     return;
> }
> 
> // Client part
> mix
>     .js('./resources/js/entry-client.js', 'public/js');
> ```

Thank you, that makes sense now! However should I put client part in `else` statement or leave it for SSR/non-SSR as you did?

**Comment by andrey-v** [comment]
@vintprox 
Да не за что ))

I use return statement at the end of the ssr if-block.

```
if (process.env.SSR === '1') {
    // some ss code...
    return; // <--- here
}

// Client code here
```
