### ISSUE TITLE
v-if mutating router-link to

### ISSUE THREAD

**Issue by WisdomEye** [spatie/laravel-server-side-rendering#34]
### Version
3.0.2

### Steps to reproduce
Just add an li using v-if, and then try change the value of variable, in the example bellow update start with value 0, I can add a button to increment or decrement it, and get error about mutating :for from router-link.

	<li v-if="update" id="dashboard-menu-top-updates">
		<router-link :to="{ name: 'Update' }" :exact="$route.name === 'Update'">Atualizações</router-link>
	</li>

### What is expected?
The expected is render or remove the element without errors about mutating ":to" from router-link

### What is actually happening?
The li is correctly rendered as wished, but make a lot of erros on console about mutating ":to" from router-link.

Error:

[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "to"

**Comment by sebastiandedeyne** [comment]
I think you meant to post this in the vue-router repo :)

https://github.com/vuejs/vue-router

**Comment by WisdomEye** [comment]
I did the post on they repo.
So they asked for the jsfiddle, and then using the jsfiddle works like desired:

[https://jsfiddle.net/WisdomEye/8uabg9so/](url)

Asking in groups people say would be about how the rendered files are made, because this have posted here.
