### ISSUE TITLE
Support Laravel 5.8

### ISSUE THREAD

**Issue by adenvt** [spatie/laravel-server-side-rendering#37]
Please add support to new Laravel 5.8

**Comment by elijahworkz** [comment]
Is there any update on this? Is it at least in the works?

**Comment by adenvt** [comment]
PR #36

**Comment by elijahworkz** [comment]
@adenvt 
Yes, I saw that after I asked the question... Thanks!

**Comment by sebastiandedeyne** [comment]
Sorry for the wait, released `1.1.0`!
