### ISSUE TITLE
error laravel ssr

### ISSUE THREAD

**Issue by Wremeker** [spatie/laravel-server-side-rendering#39]
I ran into the same problem as #23.
Php version: 7.2
Node Version: 10.15.3
System: Windows 7
My env configuration: NODE_PATH = node

Error: failed. Exit Code: 1(General error) Working directory

Ssr config:

return [
     'enabled' => true
     'debug' => true
     'mix' => true
     'engine' => \ Spatie \ Ssr \ Engines \ Node :: class,
   
     'node' => [
         'node_path' => env ('NODE_PATH', '/ usr / local / bin / node'),
         'temp_path' => storage_path ('app / ssr'),
     ],
  
     'context' => [],
     'env' => [
         'NODE_ENV' => 'production',
         'VUE_ENV' => 'server',
     ],
];

**Comment by randaleWatson** [comment]
Am not the owner of this project but since you are on windows you probably need to set 'node_path' to your node location windows location. Probably 'C:\Program Files\nodejs'
