### ISSUE TITLE
Disabling Javascript should still populate the items on DOM

### ISSUE THREAD

**Issue by kevincobain2000** [spatie/laravel-server-side-rendering#45]
Hi Spatie,

Thanks again for your great package.
I tried it using react example provided in https://github.com/spatie/laravel-server-side-rendering-examples/
I disabled javascript in the Chrome browser and the list doesn't get populated. Is that normal behavior? 
As the SEO crawlers, don't wait for JS and there are no dom elements for the list data from server added. There is however data in the ``window.PRELOADED_STATE``. My impression with SSR is that the DOM has the data that is rendered by React components before hand.

**Comment by connecteev** [comment]
+1 I'm curious whether this can be fixed for both react and vue.
