### ISSUE TITLE
Multiple entry files

### ISSUE THREAD

**Issue by zeravcic** [spatie/laravel-server-side-rendering#46]
Hello

What do you think about new feature - multiple entry files?

So,
```
{!! ssr('js/app-server.js')
    ->entry('js/app-server2.js')
    ->entry('js/app-server3.js')
    // If ssr fails, we need a container to render the app client-side
    ->fallback('<div id="app"></div>')
->render() !!}
```

Is it possible to implement some functionality like this?
Does it make sense (for existing projects)?

**Comment by sentiasa** [comment]
How will it decide which entry to use though? Either you can send the entry filename from backend as a variable or different blade files.
