### ISSUE TITLE
how to resolve the "window is not defined" problem

### ISSUE THREAD

**Issue by kertul** [spatie/laravel-server-side-rendering#47]
ReferenceError: window is not defined

Hi.
I have a problem when using the react date picker. Can you help me solve this problem?

**Comment by timrspratt** [comment]
Does the date picker inject CSS into the pages `<head>`, or bind interaction events on loading? These are typically things that components do that can't be done with SSR.

**Comment by alirezamaleky** [comment]
@kertul in ssr render and nodejs, windows doesn't defined it can only call in browser.
for import libraries that can run in browser only you must do like this:
if (typeof window !== 'undefined') {
    require('your library');
}
