### ISSUE TITLE
Can't get file from store/app/ssr

### ISSUE THREAD

**Issue by ErriourRU** [spatie/laravel-server-side-rendering#52]
I have an error: 
```
The command "node /home/site/list/test.ru/storage/app/ssr/a22a8133fc128812e26e6321cfeb1079.js" failed.
Exit Code: 1(General error)

Working directory: /home/site/list/shadowsproject.ru/public

Error Output:
================
...

ReferenceError: document is not defined
```

I've checked `store/app/ssr` folder. Files aren't created here.
All files configured like as in instruction. SSR folder exist. No any other errors appeared...

**Comment by phuongnm153** [comment]
Hi @ErriourRU,
I have a same error. Can u show your solution?

**Comment by ErriourRU** [comment]
> Hi @ErriourRU,
> I have a same error. Can u show your solution?

I haven't solution. I just started to use nuxt.

**Comment by t08-apporio** [comment]
hi @ErriourRU @phuongnm153 were you able to resolve this error?
