### ISSUE TITLE
Intergrate (Vue) ServerPrefetch Feature

### ISSUE THREAD

**Issue by canhkieu** [spatie/laravel-server-side-rendering#59]
I wanna fetch data before render. Vue srr has serverPrefetch option. It's good thing to fetch data ( from API-database) before render but it's not work. 

https://ssr.vuejs.org/guide/data.html#logic-collocation-with-components

**Comment by jcsoriano** [comment]
You don't need server prefetching, you can already provide data "while in the server" by providing context

<img width="682" alt="image" src="https://user-images.githubusercontent.com/5937317/80098631-cc2cbe00-859f-11ea-8760-75fafb73f675.png">

(screenshot from readme)
