### ISSUE TITLE
Not working when Vue component has <style>

### ISSUE THREAD

**Issue by Zolotov88** [spatie/laravel-server-side-rendering#6]
When Vue component has `<style>` than `err` is equal `ReferenceError: document is not defined` and `html` is equal `undefined`

**Comment by sebastiandedeyne** [comment]
Are you sure `style` is causing that issue? You're not referencing the DOM anywhere yourself?

If `style` is really the issue, something's wrong with vue-loader, and you'll have to file an issue there.

https://github.com/vuejs/vue-loader

This library simply executes your JavaScript, we don't do anything special that could cause that error.

**Comment by josteph** [comment]
@sebastiandedeyne Yes this behaviour is totally reproducible with the example repo provided.

https://i.imgur.com/uU0MZOF.png OR https://i.imgur.com/y0bxqKR.png

**Comment by ethor** [comment]
I am having the same issue. Did you resolve it?

**Comment by aarlandclaudel** [comment]
Hi , 
Any solution ?
