### ISSUE TITLE
SSR not working - just shows Empty screen

### ISSUE THREAD

**Issue by Seeman13** [spatie/laravel-server-side-rendering#62]
Hello! I try make ssr by Your package, but content not render on page. Errors and warning no!
Title of page is!

My code app.blade.php:
`<body>
    {{-- Entrypoints app --}}
    <script src="/_nuxt/53245307c716d2b6d1a7.js"></script>
    <script src="/_nuxt/2072e2dd77a468210c2a.js"></script>
    <script src="/_nuxt/69075bae224098322cdb.js"></script>
    <script src="/_nuxt/b4fdb60abb9b8bcc3665.js"></script>

   {{-- Entrypoint server --}}
    {!! ssr('_nuxt/server/server.js')->render() !!}
</body>`

.env
...
NODE_PATH=C:/Program%Files/nodejs/node.exe
...

![Снимок2](https://user-images.githubusercontent.com/20585416/80911817-6b407b00-8d41-11ea-8ebc-cf4d7e6b25d4.png)

**Comment by Seeman13** [comment]
Any Solutions! Thanks!

**Comment by Seeman13** [comment]
Changed APP_ENV on production, now it:
![Снимок1](https://user-images.githubusercontent.com/20585416/80915802-3f32f300-8d5d-11ea-8e8f-4d0268947ac3.png)
![Снимок2](https://user-images.githubusercontent.com/20585416/80915807-43f7a700-8d5d-11ea-980c-1007b84c72bf.png)
![Снимок3](https://user-images.githubusercontent.com/20585416/80915814-4954f180-8d5d-11ea-9cc4-8abec9e2d933.png)

**Comment by jersrej** [comment]
Hi,

I'm having the same issue but I used ReactJs, have you solved your issue?

**Comment by Seeman13** [comment]
Hello! I solved issue. I deployed project on Node Js without use this package.
