### ISSUE TITLE
SSR React with import 'style.scss' dosnt work

### ISSUE THREAD

**Issue by Dandrum** [spatie/laravel-server-side-rendering#69]
Hi,

im Using `import 'style.scss'; ` in my React components normaly thats no problem and on prod react build a css file. But on SSR i get window not found. I guess the style.scss files are saved as JS var and then get injected into header via window/document. But that dosnt work on SSR is there a way to modify laravel mix to extract styling from react components  into a single css file like normaly? I'm not that experienced with webpack itself.
My webpack mix config currently got this two.
```
 .react('frontend/entry-client.js', 'public/frontend')
 .react('frontend/entry-server.js', 'public/frontend')
```

**Comment by thomasdola** [comment]
I would rather have my `style.scss` processed by laravel mix and imported to the page where the react app is being mounted at.
This way you have your `style.css` rules available for your app to use.

I hope this helps...
