### ISSUE TITLE
Unresolvable dependency error when using V8 engine

### ISSUE THREAD

**Issue by robinvdvleuten** [spatie/laravel-server-side-rendering#7]
Hi there! When using the V8 engine, I run in the following exception;

```php
Unresolvable dependency resolving [Parameter #0 [ <optional> $object_name ]] in class V8Js
```

It looks like I can solve the issue by adding;

```php
$this->app->singleton(V8::class, function () {
    return new V8(new \V8Js());
});
```

But I do not know if that's the "Laravel" way.

**Comment by sebastiandedeyne** [comment]
Are you sure V8 is installed on your system?

**Comment by robinvdvleuten** [comment]
Yes because when I run it as mentioned in my issue it resolves without errors

**Comment by sebastiandedeyne** [comment]
Hmm didn't come across this myself, odd.

Made some IoC changes though, does the latest release (`0.2.4`) solve this?

**Comment by robinvdvleuten** [comment]
Still getting the error unfortunately with the latest version. Somehow Laravel don't detects that they are optional. Maybe it's an idea to make them configurable?

**Comment by sebastiandedeyne** [comment]
Alright, really solved this issue in `0.2.5` using your proposed snippet. Feels like the cleanest way to go :)

**Comment by robinvdvleuten** [comment]
@sebastiandedeyne thanks!

**Comment by JamesPJ** [comment]
I'm able to reproduce this issue in version `^1.3`. To make sure I'm having the `v8js` installed properly. I've cloned this https://github.com/reactjs/react-php-v8js/tree/master/example example and excecuted it locally. It worked fine.
