### ISSUE TITLE
process.env always empty

### ISSUE THREAD

**Issue by Dandrum** [spatie/laravel-server-side-rendering#70]
Im using React with this package and my process.env are always empty.

Even if i use MIX_ENVNAME or REACT_APP_ENVNAME none of them are in react. I set config/ssr env to some test values, noting arrived. I startet my project with php artisan serve and npm run poll -> nothing.
I usually use Docker and i thought its a docker problem but it might be something else.

Best,
Dan

**Comment by semihkeskindev** [comment]
You closed the issue but I have the same problem right now :smile: Did you solve it? If you did, how did you solve? What was the problem?

**Comment by Dandrum** [comment]
Hi i solved it by using next.js xDD
