### ISSUE TITLE
Target class [] does not exist. BindingResolutionException

### ISSUE THREAD

**Issue by thomasdola** [spatie/laravel-server-side-rendering#71]
Hi..

am getting `Target class [] does not exist`,  when i use 
`
{!! ssr('js/notifications/app.ssr.js')->render() !!}
`

any help?

`
"php": "^7.2.5",
"laravel/framework": "^7.24",
"spatie/laravel-server-side-rendering": "^1.4",

.env
APP_ENV=production
NODE_PATH=/usr/local/bin/node
`

**Comment by abdukhafiz** [comment]
I have the same problem.
