### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by RobertDoc** [spatie/laravel-server-side-rendering#76]
The package is not compatible with PHP 8:

    - spatie/laravel-server-side-rendering 1.4.2 requires php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.

There appears to be a PR (https://github.com/spatie/laravel-server-side-rendering/pull/75) with the necessary changes in order to make this package install on PHP 8.

Thanks!

**Comment by freekmurze** [comment]
Done!
