### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by htuzel** [spatie/laravel-server-side-rendering#88]
I am getting this error on laravel logs:

var chunkLoadingGlobal = self[\"webpackChunk\"] = self[\"webpackChunk\"] || [];

ReferenceError: self is not defined

**Comment by mreed5168** [comment]
@htuzel Try adding this to your Webpack config.

``` JS
output: {
  globalObject: typeof self !== 'undefined' ? self : 'this',
}
```

**Comment by mreed5168** [comment]
@htuzel Actually, the previous snippet will resolve the error, but SSR may not work, so I don't recommend using it. The snippet below, when added to your Webpack config, will resolve the error and builds bundles that run in any environment, so SSR will work as expected.

```JS
   output: {
      globalObject: 'this',
      libraryTarget: 'umd',
    },
```
