### ISSUE TITLE
Spatie-Laravel Server Side working absolutely fine over localhost but when I uploaded it to the server it shows ssr() is undefined Please help how to solve it?

### ISSUE THREAD

**Issue by kayAdarsh** [spatie/laravel-server-side-rendering#92]
Spatie-Laravel Server Side working absolutely fine over localhost but when I uploaded it to the server it shows ssr() is undefined Please help how to solve it?
![errorPerfect](https://user-images.githubusercontent.com/88499072/169517704-c6a1b818-a845-4c1e-bc36-4fb8feb6afd2.png)

Please help my job depends on it. Thanks in Advance

**Comment by timrspratt** [comment]
Try `composer dump-autoload` and in the future please don't tag every single contributor - this is an Open Source package - the people who contribute do not wish to feel like the future of your job is dependent on them.

**Comment by kayAdarsh** [comment]
Thanks you sir and sorry for letting you feel this way, Will keep this in mind from next time.
